server:
  port: 8081
spring:
  application:
    name: storeAPI
  datasource:
    url: jdbc:postgresql://localhost:5432/store_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql:true
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect